version: '3.6'

services:
  mysql:
    container_name: ${MYSQL_HOST}
    image: mysql:8.0.16
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_DATA_DIR}/mysql:/var/lib/mysql:rw,cached

  adminer:
    container_name: leaa-adminer
    image: adminer:4.7.1-standalone
    restart: always
    depends_on:
      - mysql
    ports:
      - ${ADMINER_PORT}:8080
